Task/6936
webduinoio/pluto-frontend pull request #12
Opened 2023-07-04 15:03 UTC by GoGoPenguin

## Description

[redmine issue](https://redmine.kingkit.codes/issues/6936)

## Motivation and Context

- 加入 [vite-plugin-basic-ssl](https://github.com/vitejs/vite-plugin-basic-ssl) 讓開發時也有 ssl，因為要讓 cookies 可以串 OAuth
- 實作 OAuth 登入
- 實作右上角 profile 視窗

## How Has This Been Tested?

## Screenshots (if appropriate)
![Untitled](https://github.com/webduinoio/pluto-frontend/assets/34542533/bc613631-ffef-48be-8d39-6cabc8982ef5)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-07-04 15:44 UTC, shengyuan requested changes

2023-07-04 15:44 UTC, shengyuan commented on src/hooks/userOAuth.ts
建議調整命名為 `useOAuth.ts`，hook 裡的命名，會是 use 開頭，有一致性。🙂

2023-07-04 15:44 UTC, shengyuan commented on src/router/index.ts
> +      ],
這裡好像可以參考[官網](https://router.vuejs.org/zh/guide/essentials/redirect-and-alias.html#%E9%87%8D%E5%AE%9A%E5%90%91)，直接 `redirect` ？

`const routes = [{ path: '/home', redirect: { name: 'homepage' } }]`

2023-07-05 00:18 UTC, shengyuan approved these changes

2023-07-05 00:30 UTC, GoGoPenguin commented on src/hooks/userOAuth.ts
打錯字，已調整

2023-07-05 00:30 UTC, GoGoPenguin commented on src/router/index.ts
> +      ],
已調整

2023-07-05 01:28 UTC, shengyuan approved these changes

2023-07-05 01:28 UTC, merged